# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.0'
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: pip test

      - name: run mainCode
        run: |
          cd bangumi.tv.v2
          python main.py

      - name: commit
        run: |
          git config --global user.email 18552541076@163.com
          git config --global user.name syxAc
          git add .
          git commit -m "update" -a

      - name: Push changes
        uses: ad-m/github-push-action@master

          
